server {
    listen 443 ssl http2;
    server_name canva-videoptimize.univ-grenoble-alpes.fr;

    ssl_certificate     /etc/ssl/canva/canva-videoptimize.univ-grenoble-alpes.fr_fullchain.pem;
    ssl_certificate_key /etc/ssl/canva/canva-videoptimize.univ-grenoble-alpes.fr.key;
    ssl_trusted_certificate /etc/ssl/canva/canva-videoptimize.univ-grenoble-alpes.fr_chain.pem;

	location /api/ {

	    # CORS headers
	    add_header Access-Control-Allow-Origin "$cors_canva_origin" always;
	    add_header Access-Control-Allow-Methods "GET, POST, OPTIONS" always;
	    add_header Access-Control-Allow-Headers "Content-Type, Authorization" always;

	    # OPTIONS must reach Express
	    if ($request_method = OPTIONS) {
	        proxy_pass http://127.0.0.1:3001;
	        break;
	    }

	    # All other methods
	    proxy_pass http://127.0.0.1:3001;
	    proxy_set_header Host $host;
	    proxy_set_header X-Real-IP $remote_addr;
	    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
	}



    # Fichiers générés
    location /tmp/ {
        alias /home/bertolino/canva_face_blurring_staging/backend/output/;
        autoindex off;
        add_header Access-Control-Allow-Origin *;
        add_header Access-Control-Allow-Headers "Content-Type, Authorization";
    }

    access_log /var/log/nginx/canva-backend-access.log;
    error_log  /var/log/nginx/canva-backend-error.log;
}

# HTTP → HTTPS
server {
    listen 80;
    server_name canva-videoptimize.univ-grenoble-alpes.fr;
    return 301 https://$host$request_uri;
}
