# HTTP → HTTPS
server {
    listen 80;
    server_name videoptimize.u-ga.fr videoptimize.univ-grenoble-alpes.fr;
    return 301 https://$host$request_uri;
}

# PRODUCTION
server {
    listen 443 ssl;
    server_name videoptimize.univ-grenoble-alpes.fr;
    client_max_body_size 50M;

    ssl_certificate     /etc/ssl/certs/videoptimize.univ-grenoble-alpes.fr_fullchain.pem;
    ssl_certificate_key /etc/ssl/private/videoptimize.univ-grenoble-alpes.fr.key;

    access_log /var/log/nginx/videoptimize-access.log;
    error_log  /var/log/nginx/videoptimize-error.log;

    location / {
        root /home/bertolino/videoptimize;
        index index.php index.html;
        try_files $uri $uri/ /index.php;
    }

    location ~ \.php$ {
        root /home/bertolino/videoptimize;
        include snippets/fastcgi-php.conf;
        fastcgi_pass unix:/run/php/php8.2-fpm.sock;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
    }

    location ~ /\.ht {
        deny all;
    }
}

# DEVELOPMENT
server {
    listen 443 ssl http2;
    server_name videoptimize.u-ga.fr;

    root /home/bertolino/videoptimize-dev;
    index index.php index.html;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        include snippets/fastcgi-php.conf;
        fastcgi_pass unix:/run/php/php8.2-fpm.sock;
    }

    ssl_certificate     /etc/ssl/certs/videoptimize.u-ga.fr_fullchain.pem;
    ssl_certificate_key /etc/ssl/private/videoptimize.u-ga.fr.key;

    access_log /var/log/nginx/videoptimize-dev-access.log;
    error_log  /var/log/nginx/videoptimize-dev-error.log;
}
